#!/bin/bash
# Register VM 126 as an org-level GitHub Actions runner and install it as a
# per-user LaunchAgent. Run over SSH from the dev box:
#
#     ssh eduin@192.168.0.245 'bash -s' < register.sh <TOKEN>
#
# Token from org eduinlight-org -> Settings -> Actions -> Runners -> New runner.
# Registration tokens expire ~1 hour after issue.
#
# NB: on macOS the runner is a LaunchAgent, NOT a daemon. It runs only inside a
# GUI login session — which is why the box is set to auto-login (see provision.sh).
# A LaunchAgent (vs daemon) is also what lets code signing work later: codesign
# needs an unlocked keychain, which only exists in a real login session.
set -euo pipefail

TOKEN="${1:?usage: register.sh <registration-token>}"
URL='https://github.com/eduinlight-org'
NAME='gh-runner-macos'
LABELS='homelab'          # self-hosted, macOS, X64 are added by GitHub
DIR="$HOME/actions-runner"
VERSION='2.336.0'

mkdir -p "$DIR"; cd "$DIR"
if [ ! -f config.sh ]; then
  curl -fsSL -o runner.tar.gz \
    "https://github.com/actions/runner/releases/download/v${VERSION}/actions-runner-osx-x64-${VERSION}.tar.gz"
  tar xzf runner.tar.gz && rm runner.tar.gz
fi

./config.sh --unattended --replace \
  --url "$URL" --token "$TOKEN" --name "$NAME" --labels "$LABELS" --work _work

# svc.sh is generated by config.sh; it must NOT be run with sudo.
./svc.sh install
./svc.sh start
./svc.sh status
