services:
  runner:
    build:
      context: .
      args:
        RUNNER_VERSION: "2.336.0"
    image: lightnotes-gh-runner:22.04
    container_name: gh-runner-docker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUNNER_URL: https://github.com/eduinlight-org
      RUNNER_NAME: gh-runner-docker
      RUNNER_LABELS: self-hosted,Linux,X64,docker,homelab
      RUNNER_EPHEMERAL: "false"
    volumes:
      - runner-home:/home/runner
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "996"

  runner-2:
    image: lightnotes-gh-runner:22.04
    container_name: gh-runner-docker-2
    restart: unless-stopped
    env_file:
      - runners.env
    environment:
      RUNNER_URL: https://github.com/eduinlight-org
      RUNNER_NAME: gh-runner-docker-2
      RUNNER_LABELS: self-hosted,Linux,X64,docker,homelab
      RUNNER_EPHEMERAL: "false"
    volumes:
      - runner-home-2:/home/runner
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "996"

  runner-3:
    image: lightnotes-gh-runner:22.04
    container_name: gh-runner-docker-3
    restart: unless-stopped
    env_file:
      - runners.env
    environment:
      RUNNER_URL: https://github.com/eduinlight-org
      RUNNER_NAME: gh-runner-docker-3
      RUNNER_LABELS: self-hosted,Linux,X64,docker,homelab
      RUNNER_EPHEMERAL: "false"
    volumes:
      - runner-home-3:/home/runner
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "996"

  runner-4:
    image: lightnotes-gh-runner:22.04
    container_name: gh-runner-docker-4
    restart: unless-stopped
    env_file:
      - runners.env
    environment:
      RUNNER_URL: https://github.com/eduinlight-org
      RUNNER_NAME: gh-runner-docker-4
      RUNNER_LABELS: self-hosted,Linux,X64,docker,homelab
      RUNNER_EPHEMERAL: "false"
    volumes:
      - runner-home-4:/home/runner
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "996"

volumes:
  runner-home:
  runner-home-2:
  runner-home-3:
  runner-home-4:
